services:
  db:
    image: postgres:16.3
    restart: always
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - url_shortener

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener_app
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 5433
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: url_shortener
    ports:
      - "3250:8080"
    depends_on:
      - db
    networks:
      - url_shortener

volumes:
  db_data:

networks:
  url_shortener:
    driver: bridge
