services:
  db:
    image: postgres:16.3
    restart: always
    container_name: url_shortener_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: url_shortener
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - url_shortener

  db_test:
    container_name: url_shortener_test_db
    image: postgres:16.3
    restart: always
    volumes:
      - db_test_data:/var/lib/postgresql/data
      - ./src/seeds/seed.sql:/docker-entrypoint-initdb.d/seed.sql
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: local
      POSTGRES_PASSWORD: local
      POSTGRES_DB: test_e2e_db

volumes:
  db_data:
  db_test_data:

networks:
  url_shortener:
    driver: bridge
